### ISSUE TITLE
CSS files are included even though the bundle is configured with the includes_* set to false

### ISSUE THREAD

**Issue by adnedelcu** [helios-ag/FMSummernoteBundle#3]
When you set configuration for bundle like so:

```YAML
fm_summernote:
    // ...
    include_jquery: false
    include_bootstrap: false
    include_fontawesome: false
```

The CSS assets are still included in the page.
I created a pull request which solves this problem (#2).
